export enum TokenSymbol {
    // SHARED
    SUMMIT = 'SUMMIT',
    EVEREST = 'EVEREST',
    USDC = 'USDC',
    
    // BSC TESTNET
    wBNB = 'wBNB',
    CAKE = 'CAKE',
    BIFI = 'BIFI',
    GS0 = 'GS0',
    GS1 = 'GS1',
    GS2 = 'GS2',
    GS3 = 'GS3',
    GS4 = 'GS4',
    GS5 = 'GS5',

    // FTM
    FTM = 'FTM',
    wFTM = 'wFTM',
    TOMB = 'TOMB',
    TOMB_FTM = 'TOMB-FTM',
    TSHARE_FTM = 'TSHARE_FTM',
    TSHARE = 'TSHARE',
    BOO = 'BOO',
    FTM_BOO = 'FTM-BOO',
    '2OMB' = '2OMB',
    '2SHARES' = '2SHARES',
    '2OMB_FTM' = '2OMB-FTM',
    '2SHARES_FTM' = '2SHARES-FTM',
    BPT_BEETS_FTM = 'BPT-BEETS-FTM',
    GRAND_ORCH = 'GRAND-ORCH',
    BATTLE_OF_THE_BANDS = 'BATTLE-OF-THE-BANDS',
    FANTOM_OF_THE_OPERA = 'FANTOM-OF-THE-OPERA',
    wETH = 'ETH',
    wBTC = 'BTC',
    fMATIC = 'MATIC',
    fAVAX = 'AVAX',
    fBNB = 'BNB',
    fLUNA = 'LUNA',
    fSOL = 'SOL',
}